// Writes src/app/primer-theme.css: the light and dark colorblind themes from @primer/primitives, reduced to the
// tokens this app references (plus the tokens those depend on). The full theme files define ~1,900 tokens, twice
// each, for every theme slot; shipping them all made the stylesheet ~5× larger than the app needs.
//
//   npm run theme   (re-run after using a new Primer token or upgrading @primer/primitives)

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const OUT = join(root, "src/app/primer-theme.css")
const themes = join(root, "node_modules/@primer/primitives/dist/css/functional/themes")
const { version } = JSON.parse(readFileSync(join(root, "node_modules/@primer/primitives/package.json"), "utf8"))

/** Token declarations of the first rule whose selector contains `selector`. */
function tokens(file, selector) {
  const css = readFileSync(join(themes, file), "utf8")
  const start = css.indexOf("{", css.indexOf(selector))
  const body = css.slice(start + 1, css.indexOf("}", start))
  return new Map([...body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)].map(m => [m[1], m[2].trim()]))
}
// The page always uses data-color-mode="auto" with these two themes, so only two of the four rules can ever apply.
const light = tokens("light-colorblind.css", '[data-color-mode="auto"][data-light-theme="light_colorblind"]')
const dark = tokens("dark-colorblind.css", '[data-color-mode][data-color-mode="auto"][data-dark-theme="dark_colorblind"]')

// Every custom property the source mentions. Names built in template literals (`--data-${c}-color-emphasis`)
// become patterns.
const files = []
const walk = dir => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p)
    else if (/\.(tsx?|css)$/.test(name) && p !== OUT) files.push(p)
  }
}
walk(join(root, "src"))
const used = new Set()
const patterns = []
for (const f of files) {
  const src = readFileSync(f, "utf8")
  for (const m of src.matchAll(/--[A-Za-z][\w-]*(?:\$\{[^}]+\}[\w-]*)+/g)) patterns.push(new RegExp(`^${m[0].replace(/\$\{[^}]+\}/g, "[\\w-]+")}$`))
  for (const m of src.matchAll(/--[A-Za-z][\w-]*/g)) used.add(m[0])
}
const wanted = name => used.has(name) || patterns.some(p => p.test(name))

/** The wanted tokens of a theme, plus everything their values reference. */
function pick(theme) {
  const keep = new Set([...theme.keys()].filter(wanted))
  for (const name of keep) for (const m of theme.get(name).matchAll(/var\((--[\w-]+)/g)) if (theme.has(m[1])) keep.add(m[1])
  return [...theme].filter(([name]) => keep.has(name))
}
const block = (entries, indent) => entries.map(([n, v]) => `${indent}${n}: ${v};`).join("\n")
const lightTokens = pick(light)
const darkTokens = pick(dark)

writeFileSync(
  OUT,
  `/* Generated by scripts/primer-theme.mjs from @primer/primitives ${version} — do not edit; run \`npm run theme\`.
   github.com's colorblind-friendly light and dark themes, reduced to the ${lightTokens.length} tokens this app uses. */
[data-color-mode="auto"][data-light-theme="light_colorblind"] {
${block(lightTokens, "  ")}
}
@media (prefers-color-scheme: dark) {
  [data-color-mode="auto"][data-dark-theme="dark_colorblind"] {
${block(darkTokens, "    ")}
  }
}
`,
)
console.log(`primer-theme.css: ${lightTokens.length} light / ${darkTokens.length} dark tokens (of ${light.size} / ${dark.size})`)
